### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by elonehoo** [livraison-dev/app#2]
This is a live list that will be updated accordingly:

- [ ] Improve the page
	- [ ] sidebar
		- [ ] search
			- [x] #3
		- [ ] settings
			- [x] feat add modal and pages #1 
			- [x] toggle dark mode and light mode #1 
			- [ ] #10
			- [ ] full width layout
			- [ ] keyboard shortcuts
			- [ ] about page
		- [ ] link clusters
	- [ ] #5
	- [ ] content
	  - [x] #8
	  - [x] input component
	  - [x] #11
	  - [ ] json preview
